apiVersion: v1
kind: Secret
metadata:
  name: mypwds
  namespace: oracle-mysql
stringData:
  rootHost: "%"
  rootPassword: supersecret
  rootUser: root
type: Opaque

---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: ic-init-from-s3-backup
spec:
  secretName: mypwds
  tlsUseSelfSigned: true
  instances: 1
  imageRepository: release-ci.daocloud.io/demo
  initDB:
    dump:
      name: "just-a-name" # 这里就是备份的名字?
      storage:
        s3:
          prefix: mgr-backup/a-cool-one-off-backup1-20231107-101739
          config: s3-secret
          bucketName: mabing
          profile: default
          endpoint: http://172.30.47.0:30926