image:
#  registry: container-registry.oracle.com |||
  registry: release-ci.daocloud.io
#  repository: mysql |||
  repository: demo
  name: community-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullSecrets:
    enabled: false
    secretName:

envs:
    imagesPullPolicy: IfNotPresent
    imagesDefaultRegistry: 
    imagesDefaultRepository:
    k8sClusterDomain: cluster.local

# If you would like to debug the Helm output with `helm template`, you need
# to turn disableLookups on as during `helm template` Helm won't contact the kube API
# and all lookups will thus fail
disableLookups: false
